# Generated by Django 6.0.4 on 2026-04-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, help_text='4桁の証券コード（例: 7203）', max_length=10, unique=True, verbose_name='証券コード')),
                ('name_ja', models.CharField(db_index=True, max_length=200, verbose_name='会社名（日本語）')),
                ('name_kana', models.CharField(blank=True, help_text='全角カタカナ', max_length=200, verbose_name='会社名（カナ）')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='会社名（英語）')),
                ('short_name_ja', models.CharField(blank=True, help_text='例: トヨタ', max_length=100, verbose_name='略称（日本語）')),
                ('industry_33', models.CharField(blank=True, choices=[('0050', '水産・農林業'), ('1050', '鉱業'), ('2050', '建設業'), ('3050', '食料品'), ('3100', '繊維製品'), ('3150', 'パルプ・紙'), ('3200', '化学'), ('3250', '医薬品'), ('3300', '石油・石炭製品'), ('3350', 'ゴム製品'), ('3400', 'ガラス・土石製品'), ('3450', '鉄鋼'), ('3500', '非鉄金属'), ('3550', '金属製品'), ('3600', '機械'), ('3650', '電気機器'), ('3700', '輸送用機器'), ('3750', '精密機器'), ('3800', 'その他製品'), ('4050', '電気・ガス業'), ('5050', '陸運業'), ('5100', '海運業'), ('5150', '空運業'), ('5200', '倉庫・運輸関連業'), ('5250', '情報・通信業'), ('6050', '卸売業'), ('6100', '小売業'), ('7050', '銀行業'), ('7100', '証券・商品先物取引業'), ('7150', '保険業'), ('7200', 'その他金融業'), ('8050', '不動産業'), ('9050', 'サービス業')], max_length=10, verbose_name='業種（33業種）')),
                ('industry_17', models.CharField(blank=True, choices=[('1', '食品'), ('2', 'エネルギー資源'), ('3', '建設・資材'), ('4', '素材・化学'), ('5', '医薬品・バイオ'), ('6', '自動車・輸送機'), ('7', '鉄鋼・非鉄'), ('8', '機械'), ('9', '電機・精機'), ('10', 'ＩＴ・サービス・その他'), ('11', '電気・ガス・水道'), ('12', '運輸・物流'), ('13', '商社・卸売'), ('14', '小売'), ('15', '銀行'), ('16', '金融（除く銀行）'), ('17', '不動産')], max_length=10, verbose_name='業種（17業種）')),
                ('scale_category', models.CharField(blank=True, choices=[('large', '大型'), ('mid', '中型'), ('small', '小型'), ('other', 'その他')], max_length=10, verbose_name='規模区分')),
                ('fiscal_year_end_month', models.CharField(blank=True, choices=[('1', '1月'), ('2', '2月'), ('3', '3月'), ('4', '4月'), ('5', '5月'), ('6', '6月'), ('7', '7月'), ('8', '8月'), ('9', '9月'), ('10', '10月'), ('11', '11月'), ('12', '12月')], max_length=2, verbose_name='決算期（月）')),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True, verbose_name='発行済株式数')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='時価総額（百万円）')),
                ('unit_shares', models.IntegerField(default=100, help_text='通常100株', verbose_name='売買単位')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('address_postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address_ja', models.CharField(blank=True, max_length=300, verbose_name='所在地（日本語）')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='所在地（英語）')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('status', models.CharField(choices=[('active', '上場中'), ('delisted', '上場廃止'), ('watchlist', '整理・監理銘柄'), ('suspended', '売買停止')], db_index=True, default='active', max_length=20, verbose_name='ステータス')),
                ('is_foreign', models.BooleanField(default=False, verbose_name='外国株')),
                ('is_etf', models.BooleanField(default=False, verbose_name='ETF / ETN')),
                ('is_reit', models.BooleanField(default=False, verbose_name='REIT / インフラファンド')),
                ('is_single_listed', models.BooleanField(default=False, help_text='東証に上場せず地方取引所のみに上場している場合はTrue', verbose_name='単独上場')),
                ('description_ja', models.TextField(blank=True, verbose_name='会社概要（日本語）')),
                ('description_en', models.TextField(blank=True, verbose_name='会社概要（英語）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '上場会社',
                'verbose_name_plural': '上場会社',
                'ordering': ['stock_code'],
            },
        ),
        migrations.CreateModel(
            name='StockExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='例: TSE, NSE, SSE, FSE', max_length=10, unique=True, verbose_name='取引所コード')),
                ('name_ja', models.CharField(max_length=100, verbose_name='取引所名（日本語）')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='取引所名（英語）')),
                ('short_name', models.CharField(blank=True, help_text='例: 東証, 名証, 札証', max_length=20, verbose_name='略称')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
            ],
            options={
                'verbose_name': '証券取引所',
                'verbose_name_plural': '証券取引所',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_segment', models.CharField(blank=True, choices=[('tse_prime', 'プライム（東証）'), ('tse_standard', 'スタンダード（東証）'), ('tse_growth', 'グロース（東証）'), ('tse_pro', 'TOKYO PRO Market'), ('tse_etf', 'ETF（東証）'), ('tse_reit', 'REIT（東証）'), ('tse_infra', 'インフラファンド（東証）'), ('nse_premier', 'プレミア（名証）'), ('nse_main', 'メイン（名証）'), ('nse_next', 'ネクスト（名証）'), ('sse_main', '本則市場（札証）'), ('sse_ambitious', 'アンビシャス（札証）'), ('sse_frontier', 'Sapporo PRO Frontier'), ('fse_main', '本則市場（福証）'), ('fse_q_board', 'Q-Board（福証）')], max_length=30, verbose_name='市場区分')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='上場日')),
                ('delisting_date', models.DateField(blank=True, null=True, verbose_name='上場廃止日')),
                ('status', models.CharField(choices=[('active', '上場中'), ('delisted', '上場廃止'), ('transferred', '市場変更')], db_index=True, default='active', max_length=20, verbose_name='上場ステータス')),
                ('notes', models.TextField(blank=True, help_text='市場区分変更の経緯など', verbose_name='備考')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.company', verbose_name='会社')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.stockexchange', verbose_name='取引所')),
            ],
            options={
                'verbose_name': '上場情報',
                'verbose_name_plural': '上場情報',
                'ordering': ['exchange__code'],
                'unique_together': {('company', 'exchange')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='exchanges',
            field=models.ManyToManyField(blank=True, related_name='companies', through='listings.Listing', to='listings.stockexchange', verbose_name='上場取引所'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['stock_code'], name='listings_co_stock_c_d5e1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name_ja'], name='listings_co_name_ja_13d617_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='listings_co_status_487a3e_idx'),
        ),
    ]
