# Generated by Django 6.0.4 on 2026-04-08 07:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_seed_exchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_etf',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_reit',
        ),
        migrations.AddField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='設立年月日'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_margin_trading',
            field=models.BooleanField(default=False, help_text='一般信用取引が可能', verbose_name='信用銘柄'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_securities_lending',
            field=models.BooleanField(default=False, help_text='制度信用取引が可能（信用銘柄の上位区分）', verbose_name='貸借銘柄'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_name',
            field=models.CharField(blank=True, help_text='例: 井上 誠', max_length=100, verbose_name='代表者氏名'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_title',
            field=models.CharField(blank=True, help_text='例: 代表取締役社長', max_length=100, verbose_name='代表者役職'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_kana',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='会社名（かな）'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='証券コード'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.company', verbose_name='会社'),
        ),
    ]
