# Generated by Django 6.0.4 on 2026-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_company_is_etf_remove_company_is_reit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_single_listed',
        ),
        migrations.AddField(
            model_name='company',
            name='earnings_date_annual',
            field=models.DateField(blank=True, null=True, verbose_name='決算発表（予定）'),
        ),
        migrations.AddField(
            model_name='company',
            name='earnings_date_q1',
            field=models.DateField(blank=True, null=True, verbose_name='第一四半期（予定）'),
        ),
        migrations.AddField(
            model_name='company',
            name='earnings_date_q2',
            field=models.DateField(blank=True, null=True, verbose_name='第二四半期（予定）'),
        ),
        migrations.AddField(
            model_name='company',
            name='earnings_date_q3',
            field=models.DateField(blank=True, null=True, verbose_name='第三四半期（予定）'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_non_jpx',
            field=models.BooleanField(default=True, help_text='東証非上場', verbose_name='東証非上場'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_foreign',
            field=models.BooleanField(default=False, help_text='外国企業の上場', verbose_name='外国株'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_margin_trading',
            field=models.BooleanField(default=False, help_text='一般信用', verbose_name='信用銘柄'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_securities_lending',
            field=models.BooleanField(default=False, help_text='制度信用', verbose_name='貸借銘柄'),
        ),
    ]
