# Generated by Django 6.0.4 on 2026-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_company_is_single_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='detail_scraped_at',
            field=models.DateTimeField(blank=True, help_text='Phase 2で詳細情報を取得した日時', null=True, verbose_name='詳細取得日時'),
        ),
    ]
