# Generated by Django 6.0.4 on 2026-04-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_company_detail_scraped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='share_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='株価（円）'),
        ),
    ]
