# Generated by Django 6.0.4 on 2026-04-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_add_share_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='yearly_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='年初来高値（円）'),
        ),
        migrations.AddField(
            model_name='company',
            name='yearly_high_date',
            field=models.DateField(blank=True, null=True, verbose_name='年初来高値日付'),
        ),
        migrations.AddField(
            model_name='company',
            name='yearly_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='年初来安値（円）'),
        ),
        migrations.AddField(
            model_name='company',
            name='yearly_low_date',
            field=models.DateField(blank=True, null=True, verbose_name='年初来安値日付'),
        ),
        migrations.AlterField(
            model_name='company',
            name='unit_shares',
            field=models.IntegerField(default=100, verbose_name='売買単位'),
        ),
    ]
