# Generated by Django 6.0.4 on 2026-04-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_add_yearly_high_low'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='株主名')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='住所')),
            ],
            options={
                'verbose_name': '株主',
                'verbose_name_plural': '株主',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='大株主順位（1〜10）', verbose_name='順位')),
                ('shares', models.BigIntegerField(blank=True, null=True, verbose_name='保有株数（百株）')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='持株比率（%）')),
                ('as_of_date', models.DateField(blank=True, help_text='株主名簿の基準日（通常は決算期末）', null=True, verbose_name='基準日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='listings.company', verbose_name='会社')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_records', to='listings.shareholder', verbose_name='株主')),
            ],
            options={
                'verbose_name': '大株主情報',
                'verbose_name_plural': '大株主情報',
                'ordering': ['company', 'rank'],
                'unique_together': {('company', 'rank')},
            },
        ),
    ]
