# Generated by Django 6.0.4 on 2026-04-10 03:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_add_shareholder_sharerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerecord',
            name='company',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_records', to='listings.company', verbose_name='会社'),
        ),
    ]
