# Generated by Django 6.0.4 on 2026-04-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_sharerecord_parentalkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='edinet_code',
            field=models.CharField(blank=True, db_index=True, help_text='例: E02167', max_length=8, verbose_name='EDINETコード'),
        ),
    ]
