# Generated by Django 6.0.4 on 2026-04-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_add_edinet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='treasury_shares',
            field=models.BigIntegerField(blank=True, help_text='EDINETより取得。市場流通株数 = 発行済株式数 − 自己株式数', null=True, verbose_name='自己株式数'),
        ),
        migrations.AlterField(
            model_name='sharerecord',
            name='shares',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='保有株数（株）'),
        ),
    ]
