# Generated by Django 6.0.4 on 2026-04-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_add_treasury_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='機関名')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='機関名（英語）')),
            ],
            options={
                'verbose_name': '親機関',
                'verbose_name_plural': '親機関',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shareholder',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shareholders', to='listings.institution', verbose_name='親機関'),
        ),
    ]
