# Generated by Django 6.0.4 on 2026-04-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_add_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='name_zh',
            field=models.CharField(blank=True, max_length=200, verbose_name='機関名（中国語）'),
        ),
    ]
