# Generated by Django 6.0.4 on 2026-04-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_add_institution_name_zh'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDINETDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='書類管理番号')),
                ('edinet_code', models.CharField(db_index=True, max_length=8, verbose_name='EDINETコード')),
                ('ordinance_code', models.CharField(max_length=10, verbose_name='府令コード')),
                ('form_code', models.CharField(max_length=10, verbose_name='様式コード')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='期間終了日')),
                ('submit_date', models.DateField(db_index=True, verbose_name='提出日')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='書類概要')),
                ('withdrawn', models.BooleanField(default=False, verbose_name='取下げ')),
            ],
            options={
                'verbose_name': 'EDINET書類',
                'verbose_name_plural': 'EDINET書類',
                'ordering': ['-submit_date'],
                'indexes': [models.Index(fields=['edinet_code', '-submit_date'], name='listings_ed_edinet__128876_idx')],
            },
        ),
    ]
