# Generated by Django 6.0.4 on 2026-04-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_company_share_price_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disclosurerecord',
            options={'ordering': ['company__stock_code', '-disclosed_date'], 'verbose_name': '適時開示', 'verbose_name_plural': '適時開示'},
        ),
        migrations.RenameIndex(
            model_name='disclosurerecord',
            new_name='listings_di_company_07c732_idx',
            old_name='listings_di_company_date_idx',
        ),
        migrations.AlterField(
            model_name='disclosurerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
