# Generated by Django 6.0.4 on 2026-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_disclosure_pdf_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='決算期末の日付。月末の場合は空欄。', null=True, verbose_name='決算期（日）'),
        ),
    ]
