# Generated by Django 6.0.4 on 2026-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_add_fiscal_year_end_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharerecord',
            options={'ordering': ['company', '-as_of_date', 'rank'], 'verbose_name': '大株主情報', 'verbose_name_plural': '大株主情報'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='market_segment',
            field=models.CharField(blank=True, choices=[('tse_prime', 'プライム（東証）'), ('tse_standard', 'スタンダード（東証）'), ('tse_growth', 'グロース（東証）'), ('tse_pro', 'TOKYO PRO Market'), ('tse_etf', 'ETF（東証）'), ('tse_reit', 'REIT（東証）'), ('tse_infra', 'インフラファンド（東証）'), ('nse_premier', 'プレミア（名証）'), ('nse_main', 'メイン（名証）'), ('nse_next', 'ネクスト（名証）'), ('sse_main', '本則市場（札証）'), ('sse_ambitious', 'アンビシャス（札証）'), ('sse_frontier', 'Sapporo PRO Frontier'), ('fse_main', '本則市場（福証）'), ('fse_q_board', 'Q-Board（福証）'), ('fse_pro_market', 'Fukuoka PRO Market（福証）')], max_length=30, verbose_name='市場区分'),
        ),
        migrations.AlterUniqueTogether(
            name='sharerecord',
            unique_together={('company', 'as_of_date', 'rank')},
        ),
    ]
