# Generated by Django 6.0.4 on 2026-04-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_majorshareholder_parentalkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='スキャン済み日付')),
            ],
            options={
                'verbose_name': 'スキャン済み日付',
                'verbose_name_plural': 'スキャン済み日付',
            },
        ),
    ]
