# Generated by Django 6.0.4 on 2026-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_others_events',
            field=models.BooleanField(default=True, verbose_name='他のユーザーのイベントを表示'),
        ),
    ]
