# Generated by Django 6.0.4 on 2026-04-20 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('start', models.DateTimeField(verbose_name='開始')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='終了')),
                ('all_day', models.BooleanField(default=False, verbose_name='終日')),
                ('description', models.TextField(blank=True, verbose_name='メモ')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cal_events', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('name', models.CharField(max_length=200, verbose_name='祝日名')),
                ('country', models.CharField(choices=[('JP', '🇯🇵 日本'), ('CN', '🇨🇳 中国'), ('US', '🇺🇸 米国')], db_index=True, default='JP', max_length=2, verbose_name='国')),
            ],
            options={
                'verbose_name': '祝日',
                'verbose_name_plural': '祝日',
                'ordering': ['date', 'country'],
                'unique_together': {('date', 'country')},
            },
        ),
    ]
