# Generated by Django 6.0.4 on 2026-04-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_memo',
            field=models.BooleanField(default=False, verbose_name='メモ/日記'),
        ),
    ]
