# Generated by Django 6.0.4 on 2026-04-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_is_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='公開'),
        ),
    ]
