# Generated by Django 6.0.4 on 2026-04-15 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0020_alter_disclosurerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_doc_id', models.CharField(help_text='EDINET document ID, e.g. S100ABCD', max_length=20, unique=True)),
                ('period_end', models.DateField(help_text='Fiscal period end date (決算期末)')),
                ('fiscal_year', models.PositiveSmallIntegerField(help_text='e.g. 2024 for FY2024')),
                ('fiscal_quarter', models.PositiveSmallIntegerField(default=4, help_text='1–4; 4 = full year')),
                ('report_type', models.CharField(choices=[('annual', 'Annual (通期)'), ('q1', 'Q1 (第1四半期)'), ('q2', 'Q2 (第2四半期)'), ('q3', 'Q3 (第3四半期)')], max_length=10)),
                ('is_consolidated', models.BooleanField(default=True, help_text='True = 連結; False = 単体')),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='listings.company')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_cf', models.BigIntegerField(blank=True, help_text='営業活動によるCF', null=True)),
                ('investing_cf', models.BigIntegerField(blank=True, help_text='投資活動によるCF', null=True)),
                ('financing_cf', models.BigIntegerField(blank=True, help_text='財務活動によるCF', null=True)),
                ('capex', models.BigIntegerField(blank=True, help_text='設備投資額 (negative = outflow)', null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_statement', to='financials.financialreport')),
            ],
            options={
                'verbose_name': 'Cash Flow Statement',
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_assets', models.BigIntegerField(blank=True, help_text='総資産', null=True)),
                ('current_assets', models.BigIntegerField(blank=True, help_text='流動資産', null=True)),
                ('non_current_assets', models.BigIntegerField(blank=True, help_text='固定資産', null=True)),
                ('cash_and_equivalents', models.BigIntegerField(blank=True, help_text='現金及び現金同等物', null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, help_text='負債合計', null=True)),
                ('current_liabilities', models.BigIntegerField(blank=True, help_text='流動負債', null=True)),
                ('interest_bearing_debt', models.BigIntegerField(blank=True, help_text='有利子負債 (short + long-term borrowings)', null=True)),
                ('net_assets', models.BigIntegerField(blank=True, help_text='純資産合計', null=True)),
                ('shareholders_equity', models.BigIntegerField(blank=True, help_text='株主資本', null=True)),
                ('equity_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='自己資本比率 (ratio)', max_digits=8, null=True)),
                ('book_value_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='一株当たり純資産 (BPS)', max_digits=12, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='financials.financialreport')),
            ],
            options={
                'verbose_name': 'Balance Sheet',
            },
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.BigIntegerField(blank=True, help_text='売上高', null=True)),
                ('gross_profit', models.BigIntegerField(blank=True, help_text='売上総利益', null=True)),
                ('operating_profit', models.BigIntegerField(blank=True, help_text='営業利益', null=True)),
                ('operating_margin', models.DecimalField(blank=True, decimal_places=4, help_text='営業利益率 (ratio, not %)', max_digits=8, null=True)),
                ('ordinary_profit', models.BigIntegerField(blank=True, help_text='経常利益', null=True)),
                ('net_income', models.BigIntegerField(blank=True, help_text='当期純利益', null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, help_text='一株当たり当期純利益 (EPS)', max_digits=12, null=True)),
                ('diluted_eps', models.DecimalField(blank=True, decimal_places=2, help_text='希薄化後EPS', max_digits=12, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, help_text='自己資本利益率 (ratio)', max_digits=8, null=True)),
                ('revenue_yoy', models.DecimalField(blank=True, decimal_places=4, help_text='Revenue YoY change (ratio)', max_digits=8, null=True)),
                ('op_profit_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='income_statement', to='financials.financialreport')),
            ],
            options={
                'verbose_name': 'Income Statement',
            },
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['company', 'period_end'], name='financials__company_003dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialreport',
            index=models.Index(fields=['fiscal_year', 'fiscal_quarter'], name='financials__fiscal__24279e_idx'),
        ),
    ]
