# Generated by Django 6.0.4 on 2026-04-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowstatement',
            name='depreciation',
            field=models.BigIntegerField(blank=True, help_text='減価償却費', null=True),
        ),
        migrations.AddField(
            model_name='incomestatement',
            name='rd_expenses',
            field=models.BigIntegerField(blank=True, help_text='研究開発費', null=True),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='capex',
            field=models.BigIntegerField(blank=True, help_text='設備投資額（設備投資等の概要より、正値）', null=True),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='net_income',
            field=models.BigIntegerField(blank=True, help_text='親会社株主に帰属する当期純利益', null=True),
        ),
    ]
