# Generated by Django 6.0.4 on 2026-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_add_depreciation_rd_capex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='interest_bearing_debt',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='bonds_payable',
            field=models.BigIntegerField(blank=True, help_text='社債（固定）', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='bonds_payable_current',
            field=models.BigIntegerField(blank=True, help_text='社債（流動）', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='commercial_paper',
            field=models.BigIntegerField(blank=True, help_text='コマーシャル・ペーパー', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='lease_obligations_current',
            field=models.BigIntegerField(blank=True, help_text='リース債務（流動）', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='lease_obligations_non_current',
            field=models.BigIntegerField(blank=True, help_text='リース債務（固定）', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='long_term_loans',
            field=models.BigIntegerField(blank=True, help_text='長期借入金', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='short_term_loans',
            field=models.BigIntegerField(blank=True, help_text='短期借入金', null=True),
        ),
    ]
