# Generated by Django 6.0.4 on 2026-04-15 08:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_financialreport_natural_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='report',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='financials.financialreport'),
        ),
        migrations.AlterField(
            model_name='cashflowstatement',
            name='report',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_statements', to='financials.financialreport'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='report',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_statements', to='financials.financialreport'),
        ),
    ]
