# Generated by Django 6.0.4 on 2026-04-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_parentalkey_for_inline_panels'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='capital_stock',
            field=models.BigIntegerField(blank=True, help_text='資本金', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='non_controlling_interests',
            field=models.BigIntegerField(blank=True, help_text='非支配株主持分', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.BigIntegerField(blank=True, help_text='利益剰余金', null=True),
        ),
    ]
