# Generated by Django 6.0.4 on 2026-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_add_dividend_paid_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dividendforecast',
            new_name='financials__company_623de4_idx',
            old_name='fin_divforecast_company_fy_idx',
        ),
        migrations.RenameIndex(
            model_name='forecastrecord',
            new_name='financials__company_295a69_idx',
            old_name='fin_forecast_company_fy_idx',
        ),
        migrations.AlterField(
            model_name='dividendforecast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forecastrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
