# Generated by Django 6.0.4 on 2026-04-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_rename_fin_divforecast_company_fy_idx_financials__company_623de4_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='shareholders_equity',
            new_name='owners_equity',
        ),
    ]
