# Generated by Django 6.0.4 on 2026-04-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0012_rename_shareholders_equity_to_owners_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='shares_issued',
            field=models.BigIntegerField(blank=True, help_text='発行済株式数（自己株式含む）', null=True),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='treasury_shares',
            field=models.BigIntegerField(blank=True, help_text='自己株式数', null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='owners_equity',
            field=models.BigIntegerField(blank=True, help_text='自己資本', null=True),
        ),
    ]
