# Generated by Django 6.0.4 on 2026-04-23 05:01

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0026_synceddate'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='リスト名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_private', models.BooleanField(default=True, verbose_name='非公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'ウォッチリスト',
                'verbose_name_plural': 'ウォッチリスト',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='listings.company')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='watchlists.watchlist')),
            ],
            options={
                'verbose_name': 'エントリー',
                'verbose_name_plural': 'エントリー',
                'ordering': ['-added_at'],
                'unique_together': {('watchlist', 'company')},
            },
        ),
        migrations.AddField(
            model_name='watchlist',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='watchlists', through='watchlists.WatchListEntry', to='listings.company'),
        ),
    ]
