# Generated by Django 6.0.4 on 2026-04-23 05:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0026_synceddate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ブローカー名')),
                ('broker_type', models.CharField(choices=[('securities', '証券会社'), ('cfd', 'CFD業者'), ('fx', 'FX業者')], default='securities', max_length=20, verbose_name='種別')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ブローカー',
                'verbose_name_plural': 'ブローカー',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='取引日')),
                ('transaction_type', models.CharField(choices=[('buy', '現物買い'), ('sell', '現物売り'), ('dividend', '配当金'), ('fee', '手数料・税'), ('deposit', '入金'), ('withdrawal', '出金')], max_length=20, verbose_name='取引種別')),
                ('asset_type', models.CharField(choices=[('cash_stock', '現物株'), ('margin', '信用取引'), ('cfd', 'CFD'), ('fx', 'FX'), ('cash', '現金')], default='cash_stock', max_length=20, verbose_name='資産種別')),
                ('symbol', models.CharField(blank=True, max_length=30, verbose_name='シンボル')),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='単価')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='手数料')),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='税金')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='金額')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='通貨')),
                ('fx_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12, verbose_name='為替レート')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.broker', verbose_name='ブローカー')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_transactions', to='listings.company', verbose_name='銘柄')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '取引',
                'verbose_name_plural': '取引',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
