# Generated by Django 6.0.4 on 2026-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(choices=[('tokutei', '特定口座'), ('ippan', '一般口座'), ('nisa_growth', 'NISA成長投資枠'), ('nisa_tsumitate', 'NISAつみたて枠')], default='tokutei', max_length=20, verbose_name='口座種別'),
        ),
    ]
